name: 'check-cross-references'
description: 'Checks checkboxes of the cross-references that are left as comments to PRs, when the referenced PR is merged.'
author: 'Ege Beysel'

# Define your inputs here.
inputs:
  token:
    description: 'API Token for the Github API Calls'
    required: true

runs:
  using: node20
  main: dist/index.js
